name: Build and Test Serverless Packaging

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pipenv==2023.7.4
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test Serverless packaging
        run: |
          npm -g install serverless@3
          serverless create --template-path . --path="/tmp/app-aws-cost" --name="app-aws-cost"
          cd /tmp/app-aws-cost
          serverless plugin install -n serverless-python-requirements
          serverless package --stage="prod" --param="slack_url=https://hooks.slack.com/services/xxx/yyy/zzzz"
